-- Intentionally empty. The v3 design (frontend Zustand welcome-store) replaced
-- the v2 persisted runtime choice columns; rolling this migration back has no
-- meaningful target state. Re-introducing the columns would also re-introduce
-- the deleted CHECK constraint, OnboardingService.MarkComplete plumbing, and
-- PATCH /api/me/onboarding runtime field handling — none of which exist in
-- the current code.
